
GET http://localhost:5015/games

###

GET http://localhost:5015/games/3


###

POST http://localhost:5015/games
Content-Type: application/json

{
   "name":"Into the unkown unending void",
    "genreId":3,
    "price":90.9,
    "releaseDate":"2024-11-13"

}

###
PUT http://localhost:5015/games/3
Content-Type: application/json

{
    "name":"Aura-Theme",
    "genreId":3,
    "price":102.9,
    "releaseDate":"2025-11-18"

}


###

DELETE http://localhost:5015/games/5