
GET http://localhost:5015/games

###

GET http://localhost:5015/games/3

###

POST http://localhost:5015/games
Content-Type: application/json

{
   "name":"Candy Crush",
    "genreId":3,
    "price":12.9,
    "releaseDate":"2011-11-18"

}

###
PUT http://localhost:5015/games/3
Content-Type: application/json

{
    "name":"Aura-Theme",
    "genreId":3,
    "price":102.9,
    "releaseDate":"2025-11-18"

}


###

DELETE http://localhost:5015/games/5